/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve */
        get: operations["resolve_companies_resolve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Digest */
        get: operations["latest_digest_digest_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Digest For Date */
        get: operations["digest_for_date_digest__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{cik}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prices */
        get: operations["prices_companies__cik__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Companies Returns */
        get: operations["companies_returns_companies_returns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/latest-prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Companies Latest Prices */
        get: operations["companies_latest_prices_companies_latest_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{cik}/filing-signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filing Signals */
        get: operations["filing_signals_companies__cik__filing_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{cik}/financial-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Financial Metrics */
        get: operations["financial_metrics_companies__cik__financial_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{cik}/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** News */
        get: operations["news_companies__cik__news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{cik}/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Price Anomalies */
        get: operations["price_anomalies_companies__cik__anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomalies/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Price Anomalies */
        get: operations["latest_price_anomalies_anomalies_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Agent */
        post: operations["ask_agent_agent_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentAnswerOut */
        AgentAnswerOut: {
            /** Answer */
            answer: string;
        };
        /** AgentQuery */
        AgentQuery: {
            /** Question */
            question: string;
            /** Thread Id */
            thread_id: string;
            /** Selected Company */
            selected_company?: {
                [key: string]: unknown;
            } | null;
        };
        /** AnomalyOut */
        AnomalyOut: {
            /** Cik */
            cik: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Return Pct */
            return_pct: number;
            /** Z Score */
            z_score: number;
            /** Explanation */
            explanation: string | null;
            /** Explained At */
            explained_at: string | null;
        };
        /** CompanyOut */
        CompanyOut: {
            /** Cik */
            cik: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Industry Segment */
            industry_segment: string;
            /** Reporting Currency */
            reporting_currency: string;
            /** Aliases */
            aliases: string[];
            /** News Disambiguation */
            news_disambiguation: string[];
        };
        /** CompanyReturnsOut */
        CompanyReturnsOut: {
            /** Returns */
            returns: {
                [key: string]: number | null;
            };
        };
        /** DigestBenchmarksOut */
        DigestBenchmarksOut: {
            /** Soxx Return */
            soxx_return: number | null;
            /** Smh Return */
            smh_return: number | null;
            /** Spy Return */
            spy_return: number | null;
        };
        /** DigestCompanyOut */
        DigestCompanyOut: {
            /** Cik */
            cik: string;
            /** Industry Segment */
            industry_segment: string;
            /** Return Pct */
            return_pct: number | null;
            /** Peer Avg Return Pct */
            peer_avg_return_pct: number | null;
            /** Vs Peer Avg */
            vs_peer_avg: number | null;
            /** Vs Soxx */
            vs_soxx: number | null;
            /** Vs Smh */
            vs_smh: number | null;
            /** Vs Spy */
            vs_spy: number | null;
            /** Cross Sectional Z Score */
            cross_sectional_z_score: number | null;
            /** Is Cross Sectional Anomaly */
            is_cross_sectional_anomaly: boolean;
        };
        /** DigestOut */
        DigestOut: {
            /** Companies */
            companies: components["schemas"]["DigestCompanyOut"][];
            benchmarks: components["schemas"]["DigestBenchmarksOut"];
        };
        /** FilingSignalOut */
        FilingSignalOut: {
            /** Accession Number */
            accession_number: string;
            /** Form */
            form: string;
            /**
             * Filed Date
             * Format: date
             */
            filed_date: string;
            /** Guidance Commentary */
            guidance_commentary: string | null;
            /** Segment Commentary */
            segment_commentary: string | null;
            /** Executive Quote Summary */
            executive_quote_summary: string | null;
            /** Mentioned Customers */
            mentioned_customers: string[];
            /** Mentioned Competitors */
            mentioned_competitors: string[];
        };
        /** FinancialMetricOut */
        FinancialMetricOut: {
            /** Tag */
            tag: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Period Type */
            period_type: string;
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /** Form */
            form: string;
            /**
             * Filed Date
             * Format: date
             */
            filed_date: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LatestPricesOut */
        LatestPricesOut: {
            [key: string]: number | null;
        };
        /** NewsArticleOut */
        NewsArticleOut: {
            /** Cik */
            cik: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Author */
            author: string | null;
            /** Published At */
            published_at: string | null;
        };
        /** ResolvedCompanyOut */
        ResolvedCompanyOut: {
            /** Cik */
            cik: string;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Industry Segment */
            industry_segment: string;
            /** Reporting Currency */
            reporting_currency: string;
            /** Aliases */
            aliases: string[];
            /** News Disambiguation */
            news_disambiguation: string[];
            /** Match Confidence */
            match_confidence: number;
        };
        /** StockPriceOut */
        StockPriceOut: {
            /** Cik */
            cik: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_companies_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
        };
    };
    resolve_companies_resolve_get: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedCompanyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_digest_digest_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
        };
    };
    digest_for_date_digest__date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prices_companies__cik__prices_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path: {
                cik: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockPriceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    companies_returns_companies_returns_get: {
        parameters: {
            query: {
                start_date: string;
                end_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyReturnsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    companies_latest_prices_companies_latest_prices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestPricesOut"];
                };
            };
        };
    };
    filing_signals_companies__cik__filing_signals_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                cik: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilingSignalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    financial_metrics_companies__cik__financial_metrics_get: {
        parameters: {
            query?: {
                tag?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                cik: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialMetricOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    news_companies__cik__news_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                cik: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsArticleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    price_anomalies_companies__cik__anomalies_get: {
        parameters: {
            query?: {
                limit?: number;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path: {
                cik: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_price_anomalies_anomalies_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyOut"][];
                };
            };
        };
    };
    ask_agent_agent_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
