"""initial schema

Revision ID: f2c6f9eaacd2
Revises:
Create Date: 2026-07-27 00:44:45.868790

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2c6f9eaacd2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("cik", sa.String(length=10), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("subarea", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("cik"),
    )
    op.create_index(
        op.f("ix_companies_subarea"), "companies", ["subarea"], unique=False
    )
    op.create_index(op.f("ix_companies_ticker"), "companies", ["ticker"], unique=True)
    op.create_table(
        "filing_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cik", sa.String(length=10), nullable=False),
        sa.Column("accession_number", sa.String(length=25), nullable=False),
        sa.Column("form", sa.String(length=10), nullable=False),
        sa.Column("item_type", sa.String(length=10), nullable=True),
        sa.Column("filed_date", sa.Date(), nullable=False),
        sa.Column("guidance_commentary", sa.String(), nullable=True),
        sa.Column("segment_commentary", sa.String(), nullable=True),
        sa.Column("executive_quote_summary", sa.String(), nullable=True),
        sa.Column("mentioned_customers", sa.String(), nullable=True),
        sa.Column("mentioned_competitors", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["cik"],
            ["companies.cik"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_filing_signals_accession_number"),
        "filing_signals",
        ["accession_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_filing_signals_cik"), "filing_signals", ["cik"], unique=False
    )
    op.create_table(
        "financial_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cik", sa.String(length=10), nullable=False),
        sa.Column("tag", sa.String(length=100), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period_type", sa.String(length=10), nullable=False),
        sa.Column("value", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("form", sa.String(length=10), nullable=False),
        sa.Column("accession_number", sa.String(length=25), nullable=False),
        sa.Column("filed_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cik"],
            ["companies.cik"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cik",
            "tag",
            "period_start",
            "period_end",
            "form",
            name="uq_financial_metric_period",
        ),
    )
    op.create_index(
        op.f("ix_financial_metrics_cik"), "financial_metrics", ["cik"], unique=False
    )
    op.create_index(
        op.f("ix_financial_metrics_period_end"),
        "financial_metrics",
        ["period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_metrics_tag"), "financial_metrics", ["tag"], unique=False
    )
    op.create_table(
        "pending_edges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_cik", sa.String(length=10), nullable=False),
        sa.Column("target_name", sa.String(length=255), nullable=False),
        sa.Column("edge_type", sa.String(length=20), nullable=False),
        sa.Column("evidence_accession_number", sa.String(length=25), nullable=False),
        sa.Column("evidence_snippet", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["source_cik"],
            ["companies.cik"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pending_edges")
    op.drop_index(op.f("ix_financial_metrics_tag"), table_name="financial_metrics")
    op.drop_index(
        op.f("ix_financial_metrics_period_end"), table_name="financial_metrics"
    )
    op.drop_index(op.f("ix_financial_metrics_cik"), table_name="financial_metrics")
    op.drop_table("financial_metrics")
    op.drop_index(op.f("ix_filing_signals_cik"), table_name="filing_signals")
    op.drop_index(
        op.f("ix_filing_signals_accession_number"), table_name="filing_signals"
    )
    op.drop_table("filing_signals")
    op.drop_index(op.f("ix_companies_ticker"), table_name="companies")
    op.drop_index(op.f("ix_companies_subarea"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
